name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Upload code coverage
      uses: codecov/codecov-action@v1

    - name: Push package to Nuget
      run: dotnet nuget push src/NzCovidPass.Core/bin/Release/NzCovidPass.Core.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate